services:
#    rmatil_cms.example:
#        class: rmatil\CmsBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    rmatil_cms.factory.json_response:
        class: rmatil\CmsBundle\Response\JsonResponseFactory
        arguments: ['@jms_serializer']

    rmatil_cms.data_accessor.article_category:
        class: rmatil\CmsBundle\DataAccessor\DataAccessor
        arguments: ['rmatilCmsBundle:ArticleCategory', '@doctrine.orm.entity_manager', '@security.token_storage', '@logger']

    rmatil_cms.data_accessor.article:
        class: rmatil\CmsBundle\DataAccessor\ArticleDataAccessor
        arguments: ['@doctrine.orm.entity_manager', '@rmatil_cms.mapper.article_mapper', '@security.token_storage', '@logger']

    rmatil_cms.data_accessor.page:
        class: rmatil\CmsBundle\DataAccessor\PageDataAccessor
        arguments: ['@doctrine.orm.entity_manager', '@rmatil_cms.mapper.page_mapper', '@security.token_storage', '@logger']

    rmatil_cms.data_accessor.event:
        class: rmatil\CmsBundle\DataAccessor\EventDataAccessor
        arguments: ['@doctrine.orm.entity_manager', '@rmatil_cms.mapper.event_mapper', '@security.token_storage', '@logger']

    rmatil_cms.data_accessor.file:
        class: rmatil\CmsBundle\DataAccessor\FileDataAccessor
        arguments: ['@doctrine.orm.entity_manager', '@rmatil_cms.mapper.file_mapper', '@vich_uploader.templating.helper.uploader_helper', '@security.token_storage', '@logger']

    rmatil_cms.mapper.article_category_mapper:
        class: rmatil\CmsBundle\Mapper\ArticleCategoryMapper

    rmatil_cms.mapper.language_mapper:
        class: rmatil\CmsBundle\Mapper\LanguageMapper

    rmatil_cms.mapper.user_group_mapper:
        class: rmatil\CmsBundle\Mapper\UserGroupMapper

    rmatil_cms.mapper.user_mapper:
        class: rmatil\CmsBundle\Mapper\UserMapper

    rmatil_cms.mapper.article_mapper:
        class: rmatil\CmsBundle\Mapper\ArticleMapper
        arguments: ['@rmatil_cms.mapper.article_category_mapper', '@rmatil_cms.mapper.language_mapper', '@rmatil_cms.mapper.user_group_mapper', '@rmatil_cms.mapper.user_mapper']

    rmatil_cms.mapper.page_mapper:
        class: rmatil\CmsBundle\Mapper\PageMapper
        arguments: ['@rmatil_cms.mapper.article_mapper', '@rmatil_cms.mapper.language_mapper', '@rmatil_cms.mapper.user_group_mapper', '@rmatil_cms.mapper.user_mapper']

    rmatil_cms.mapper.file_mapper:
        class: rmatil\CmsBundle\Mapper\FileMapper
        arguments: ['@rmatil_cms.mapper.user_mapper']

    rmatil_cms.mapper.repeat_option:
        class: rmatil\CmsBundle\Mapper\RepeatOptionMapper

    rmatil_cms.mapper.event_mapper:
        class: rmatil\CmsBundle\Mapper\EventMapper
        arguments: ['@rmatil_cms.mapper.user_mapper', '@rmatil_cms.mapper.file_mapper', '@rmatil_cms.mapper.location_mapper', '@rmatil_cms.mapper.repeat_option', '@rmatil_cms.mapper.user_group_mapper']

    rmatil_cms.mapper.location_mapper:
        class: rmatil\CmsBundle\Mapper\LocationMapper

    rmatil_cms.security.restrictable_voter:
        class: rmatil\CmsBundle\Security\RestrictableVoter
        arguments: ['@security.access.decision_manager', '@security.role_hierarchy']
        public: false
        tags:
            - { name: security.voter }
